# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lfsrc_harness.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 7, 35, 1, "", "lfsrc_harness.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x13lfsrc_harness.proto\x12\x05lfsrc"\x1c\n\x0cJsonEnvelope\x12\x0c\n\x04json\x18\x01 \x01(\x0c\x32\x38\n\x05\x41gent\x12/\n\x03Run\x12\x13.lfsrc.JsonEnvelope\x1a\x13.lfsrc.JsonEnvelopeb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "lfsrc_harness_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_JSONENVELOPE"]._serialized_start = 30
    _globals["_JSONENVELOPE"]._serialized_end = 58
    _globals["_AGENT"]._serialized_start = 60
    _globals["_AGENT"]._serialized_end = 116
# @@protoc_insertion_point(module_scope)
